### PR TITLE
Fix code to work with dmd 2.083

### PR DESCRIPTION
**Pull request by Marenz**

### CODE REVIEW

**Comment by msoucy** [comment]
Can you demonstrate how this breaks? It seems to work fine for me with dmd 2.086

**Comment by Marenz** [comment]
Did you use the dev-1.x branch?

**Comment by msoucy** [comment]
Yes - there are several deprecations (not surprising, considering that I haven't touched the 1.x branch in years, and wouldn't recommend anyone use it) but running a `dub test` still passes successfully.

Per [19.16.8.3](https://dlang.org/spec/function.html#typesafe_variadic_functions) of the dlang standard, the code you modify is correct.

Please provide a sample that shows how the current code breaks using the latest compiler, that is fixed by your patch, so I can see what behavior causes problems.

**Comment by Marenz** [comment]
> wouldn't recommend anyone use it

I have to use it because the 2.x version [removed a feature](https://github.com/msoucy/dproto/issues/80) that I needed in my projects

Specifcally, I am getting this error:
```
../../.dub/packages/dproto-1.3.2/dproto/import/dproto/buffers.d(297,7): Error: scope variable val assigned to this with longer lifetime
```

running a simple `dub test` in the dproto causes this error. I ran it with dmd 2.083.1

**Comment by Marenz** [comment]
hmm indeed, the error is gone on the newer dmds..

**Comment by msoucy** [comment]
I can't find which version fixed it, but it is indeed fixed in 2.086.0
